"""O que seu módulo faz

testandoooooooooooooooooooooooooooooo
askdopáskdoksada
asdkopáskdasdsdsdsdsladasdlaśldpaślpdaśpldapldpasdpdlapdlasldasápldapdlaspdlap
aslkpadlasldasdasdlsadlspaddlpasa´dpasdsadlaspdasdpapdad
asldpasldplaspdlspldspdlpsldspdlspdspdppsdlwspsplpldpspldplsdplpspldplspdlpslpd
spldpslpdlpslpdlpslpdplspldplspldplspldpslpdlpsldplps

"""